name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      # checkout the repo
      - name: Checkout
        uses: actions/checkout@v2

      # setup node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # cache node_modules
      - name: Cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # install dependencies
      - name: Install
        run: yarn --prefer-offline --frozen-lockfile

      # build
      - name: Build
        run: yarn build

      - name: Deploy
        uses: convictional/gcp-storage-action@master
        with:
          application_credentials: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          command: gcloud builds submit

        env:
          API_AUTH: ${{ secrets.API_AUTH }}
          DOOR_FLOOR: ${{ secrets.DOOR_FLOOR }}
          DOOR_STREET: ${{ secrets.DOOR_STREET }}
          NUKI_TOKEN: ${{ secrets.NUKI_TOKEN }}
